/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ledger/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anchors */
        get: operations["ledger_list_anchors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Event Types
         * @description The vocabulary, so clients do not hard-code it.
         */
        get: operations["ledger_list_event_types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Recorded events, newest first, optionally filtered.
         */
        get: operations["ledger_list_events"];
        put?: never;
        /**
         * Append
         * @description Append one event. Internal services only.
         */
        post: operations["ledger_append_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/events/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["ledger_get_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Head
         * @description Current chain head — the cheapest integrity check available.
         */
        get: operations["ledger_head"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify
         * @description Re-derive every hash and report any break in the chain.
         */
        get: operations["ledger_verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness probe: database reachable and schema up to date.
         */
        get: operations["system_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description What is actually deployed here.
         */
        get: operations["system_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnchorOut */
        AnchorOut: {
            /** Anchored At */
            anchored_at: string | null;
            /** Chain */
            chain: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Count */
            event_count: number;
            /** First Seq */
            first_seq: number;
            /** Head Hash */
            head_hash: string;
            /** Last Seq */
            last_seq: number;
            /** Merkle Root */
            merkle_root: string;
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Status */
            status: string;
            /** Tx Hash */
            tx_hash: string;
        };
        /** ChainProblemOut */
        ChainProblemOut: {
            /** Reason */
            reason: string;
            /** Seq */
            seq: number;
        };
        /** ChainReportOut */
        ChainReportOut: {
            /** Checked */
            checked: number;
            /** Head Hash */
            head_hash: string;
            /** Head Seq */
            head_seq: number;
            /** Ok */
            ok: boolean;
            /** Problems */
            problems: components["schemas"]["ChainProblemOut"][];
        };
        /** DynamicInput */
        DynamicInput: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
        };
        /**
         * EventIn
         * @description An append request from an internal service.
         */
        EventIn: {
            /** Actor */
            actor?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Subject
             * @default
             */
            subject: string;
            /** Type */
            type: string;
        };
        /** EventOut */
        EventOut: {
            /** Actor */
            actor: string | null;
            /** Hash */
            hash: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Payload Hash */
            payload_hash: string;
            /** Prev Hash */
            prev_hash: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Seq */
            seq: number;
            /** Signature */
            signature: string;
            /** Subject */
            subject: string;
            /** Type */
            type: string;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /** EventTypeOut */
        EventTypeOut: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** HeadOut */
        HeadOut: {
            /** Event Count */
            event_count: number;
            /** Hash */
            hash: string;
            /** Seq */
            seq: number;
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Migrations Pending */
            migrations_pending: number | null;
            /** Status */
            status: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** PaginatedResponseSchema[EventOut] */
        PaginatedResponseSchema_EventOut_: {
            /** Count */
            count: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["EventOut"][];
        };
        /** VersionOut */
        VersionOut: {
            /** Api Version */
            api_version: string;
            /** Commit */
            commit: string | null;
            /** Environment */
            environment: string;
            /** Service */
            service: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ledger_list_anchors: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"][];
                };
            };
        };
    };
    ledger_list_event_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeOut"][];
                };
            };
        };
    };
    ledger_list_events: {
        parameters: {
            query?: {
                type?: string | null;
                subject?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseSchema_EventOut_"];
                };
            };
        };
    };
    ledger_append_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
        };
    };
    ledger_get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
        };
    };
    ledger_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadOut"];
                };
            };
        };
    };
    ledger_verify: {
        parameters: {
            query?: {
                since_seq?: number;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainReportOut"];
                };
            };
        };
    };
    system_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    system_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
        };
    };
}
