[pytest]
DJANGO_SETTINGS_MODULE = bbsbackend.settings.test
python_files = test_*.py
testpaths = tests
addopts = -q --strict-markers
filterwarnings =
    error::DeprecationWarning:apps.*
    error::DeprecationWarning:bbsbackend.*
