# Generated by Django 6.1.1 on 2026-09-08 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.SlugField(max_length=64, unique=True)),
                ('actor_type', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('device', 'Device'), ('system', 'System')], max_length=16)),
                ('public_key', models.CharField(blank=True, default='', help_text='Ed25519 public key, 32 bytes hex-encoded.', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'actor key',
                'verbose_name_plural': 'actor keys',
                'db_table': 'ledger_actor_key',
                'ordering': ['handle'],
            },
        ),
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='UTC date covered.', unique=True)),
                ('first_seq', models.BigIntegerField()),
                ('last_seq', models.BigIntegerField()),
                ('event_count', models.PositiveIntegerField()),
                ('merkle_root', models.CharField(max_length=64)),
                ('head_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', help_text='Chain head at the moment of anchoring.', max_length=64)),
                ('chain', models.CharField(blank=True, default='', max_length=32)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('anchored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_anchor',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('perception.captured', 'Perception captured'), ('artifact.stored', 'Artifact stored'), ('brief.drafted', 'Brief drafted'), ('estimate.proposed', 'Estimate proposed'), ('agent.run.started', 'Agent run started'), ('agent.tool.called', 'Agent tool called'), ('agent.run.finished', 'Agent run finished'), ('human.approved', 'Human approved'), ('human.rejected', 'Human rejected'), ('commit.pushed', 'Commit pushed'), ('milestone.delivered', 'Milestone delivered'), ('client.accepted', 'Client accepted'), ('invoice.issued', 'Invoice issued'), ('escrow.funded', 'Escrow funded'), ('escrow.released', 'Escrow released'), ('yield.accrued', 'Yield accrued'), ('anchor.created', 'Anchor created'), ('system.note', 'System note')], db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, db_index=True, default='', help_text="What this is about, e.g. 'engagement:42' or 'milestone:7'.", max_length=200)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the fact happened.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When the ledger learned of it.')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('signature', models.CharField(blank=True, default='', help_text='Ed25519 signature over the event hash, 64 bytes hex-encoded.', max_length=128)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ledger.actorkey')),
            ],
            options={
                'db_table': 'ledger_event',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['type', 'occurred_at'], name='ledger_type_time_idx'), models.Index(fields=['subject', 'seq'], name='ledger_subject_seq_idx')],
            },
        ),
    ]
